--
-- SCRIPT PARA LA EJECUCION INICIAL DE LOS PROCESOS, SE EJECUTA POR UNICA VEZ
--
-- CGN_STATS_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/CGN_STATS_EndToEnd.kjb','2306201714','2306201714',5,'Hourly','CISCO_PRIME');
-- INTERFACE_AVAIL_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/INTERFACE_AVAIL_EndToEnd.kjb','2306201714','2306201714',5,'Hourly','CISCO_PRIME');
-- INTERFACE_ERRORS_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/INTERFACE_ERRORS_EndToEnd.kjb','2306201714','2306201714',5,'Hourly','CISCO_PRIME');
-- INTERFACE_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/INTERFACE_EndToEnd.kjb','2306201714','2306201714',5,'Hourly','CISCO_PRIME');
-- CPU_MEM_DEVICE_AVG_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/CPU_MEM_DEVICE_AVG_EndToEnd.kjb','2306201714','2306201714',5,'Hourly','CISCO_PRIME');



INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/Rework/INTERFACE_ERRORS_RWK_EndToEnd.kjb',CASE
            WHEN SYSDATE < TRUNC(SYSDATE,'HH24') + (ROUND((SYSDATE - TRUNC (SYSDATE))* 48)/ 48) THEN to_char(SYSDATE-1/24,'DDMMYYYYHH24')
            ELSE
              to_char(TRUNC(SYSDATE) + (ROUND((SYSDATE - TRUNC (SYSDATE))*48)/48),'DDMMYYYYHH24')
          END,'2306201714',5,'Hourly','RWK_CISCO_PRIME');


CREATE OR REPLACE PROCEDURE P_INSERT_RWK_PROCESS( P_PROCESS_NAME  IN VARCHAR2,
                                                  P_PARAMS        IN VARCHAR2,
                                                  P_TIPO          IN VARCHAR2,
                                                  P_GRUPO         IN VARCHAR2,
                                                  P_VARIABLE      IN VARCHAR2 DEFAULT NULL) AS
  V_FECHA_TO_PROCESS  VARCHAR2(10 CHAR) := '';
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_FORMAT = ''DD.MM.YYYY HH24:MI:SS''';
  --  
  SELECT  CASE
            WHEN TRUNC(SYSDATE,'HH24') < TRUNC(SYSDATE,'HH24') + (ROUND((SYSDATE - TRUNC (SYSDATE))* 48)/ 48) THEN to_char(SYSDATE-1/24,'DDMMYYYYHH24')
            ELSE
              to_char(TRUNC(SYSDATE) + (ROUND((SYSDATE - TRUNC (SYSDATE))*48)/48),'DDMMYYYYHH24')
          END FECHA_TO_PROCESS
        
  FROM    DUAL;
  --
  INSERT INTO PROCESS_TO_RUN(  PROCESS_NAME,  PARAMS,  FECHA_TO_RUN,  TIPO,  GRUPO,  STATUS)
  VALUES(P_PROCESS_NAME,P_PARAMS,V_FECHA_TO_PROCESS,P_TIPO,P_GRUPO,5);

END P_INSERT_RWK_PROCESS;


select 'ALTER TABLE LTE_NSN_SERVICE_LCEL_HOUR MOVE SUBPARTITON '||DATO.subpartition_name|| ' TABLESPACE TBS_HOUR UPDATE INDEXES;'
FROM (
SELECT table_name,
       partition_name,
       subpartition_name,
       num_rows
FROM   user_tab_subpartitions
where table_name = 'LTE_NSN_SERVICE_LCEL_HOUR'
ORDER BY 1,2,3) DATO;