--
-- SCRIPT PARA LA EJECUCION INICIAL DE LOS PROCESOS, SE EJECUTA POR UNICA VEZ
--
-- CGN_STATS_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/CGN_STATS_EndToEnd.kjb','0806201710','0806201710',5,'Hourly','CISCO_PRIME');
-- INTERFACE_AVAIL_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/INTERFACE_AVAIL_EndToEnd.kjb','0806201710','0806201710',5,'Hourly','CISCO_PRIME');
-- INTERFACE_ERRORS_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/INTERFACE_ERRORS_EndToEnd.kjb','0806201710','0806201710',5,'Hourly','CISCO_PRIME');
-- INTERFACE_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/INTERFACE_EndToEnd.kjb','0806201710','0806201710',5,'Hourly','CISCO_PRIME');
-- CPU_MEM_DEVICE_AVG_HOUR Process
INSERT INTO PROCESS_TO_RUN (PROCESS_NAME,PARAMS,FECHA_TO_RUN,STATUS,TIPO,GRUPO) VALUES
('/calidad/CiscoPrime/PentahoSourceFiles/CPU_MEM_DEVICE_AVG_HOUR_EndToEnd.kjb','0806201710','0806201710',5,'Hourly','CISCO_PRIME');

